openai:
  api_key: gsk-eyJjb2dlbl9pZCI6ImIxZmRmMDY0LWM3MDQtNDBhYi04MTJlLThkNzRhMWY3ZWMzNiIsImtleV9pZCI6ImRmMTc3NzY1LWY4YTktNGZkMC04ZjZiLTkxZTVmYmY5ZmMyZSIsImN0aW1lIjoxNzc1ODM0NTMzLCJjbGF1ZGVfYmlnX21vZGVsIjpudWxsLCJjbGF1ZGVfbWlkZGxlX21vZGVsIjpudWxsLCJjbGF1ZGVfc21hbGxfbW9kZWwiOm51bGx9fAN1SrFhd2Ers7uk9LCC07BYM13mxysGdxFVzPBUISXs
  base_url: https://www.genspark.ai/api/llm_proxy/v1
