package com.heapdump.analyzer.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.Map;

@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CoreDumpAnalysisResult {
    private String filename;
    private String executableName;
    private String gdbVersion;
    private String crashSignal;           // "SIGSEGV", "SIGABRT" 등
    private String signalDescription;     // "Segmentation fault" 등
    private String coreProgramName;       // Core was generated by 에서 추출
    private List<GdbStackFrame> mainBacktrace;
    private List<GdbThreadInfo> allThreads;
    private Map<String, String> registers;
    private List<GdbSharedLib> sharedLibraries;
    private String gdbRawOutput;
    private String coreDumpTime;          // 코어 파일 생성 시각 (파일 mtime)
    private String errorMessage;
    private String analyzedAt;            // ISO-8601 문자열
    private long analysisTimeMs;

    // ── 분석 신뢰도 메타 (심볼 없는/손상된 스택 대응) ──────────────
    private String analysisConfidence;       // "HIGH" | "MEDIUM" | "LOW"
    private List<String> qualityWarnings;    // 신뢰도 저하 사유(한국어) 목록
    private int resolvedFrameCount;          // 심볼 해석된(RESOLVED) 프레임 수
    private int totalFrameCount;             // 메인 백트레이스 총 프레임 수
    private boolean symbolsAvailable;        // 심볼/공유라이브러리 심볼 존재 여부
    private GdbStackFrame firstResolvedFrame; // 최초 RESOLVED 프레임(없으면 null)
}
