package com.heapdump.analyzer.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.Map;

@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CoreDumpAnalysisResult {
    private String filename;
    private String executableName;
    private String gdbVersion;
    private String crashSignal;           // "SIGSEGV", "SIGABRT" 등
    private String signalDescription;     // "Segmentation fault" 등
    private String coreProgramName;       // Core was generated by 에서 추출
    private List<GdbStackFrame> mainBacktrace;
    private List<GdbThreadInfo> allThreads;
    private Map<String, String> registers;
    private List<GdbSharedLib> sharedLibraries;
    private List<String> memoryMappings;      // info proc mappings (NT_FILE) — 파일-백트 매핑 행
    private List<String> crashDisassembly;    // x/16i $pc — 크래시 지점 명령어 라인
    private String gdbRawOutput;
    private String coreDumpTime;          // 코어 파일 생성 시각 (파일 mtime)
    private String errorMessage;
    private String analyzedAt;            // ISO-8601 문자열
    private long analysisTimeMs;

    // ── 분석 신뢰도 메타 (심볼 없는/손상된 스택 대응) ──────────────
    private String analysisConfidence;       // "HIGH" | "MEDIUM" | "LOW"
    private List<String> qualityWarnings;    // 신뢰도 저하 사유(한국어) 목록
    private int resolvedFrameCount;          // 심볼 해석된(RESOLVED) 프레임 수
    private int totalFrameCount;             // 메인 백트레이스 총 프레임 수
    private boolean symbolsAvailable;        // 심볼/공유라이브러리 심볼 존재 여부
    private GdbStackFrame firstResolvedFrame; // 최초 RESOLVED 프레임(없으면 null)

    // ── 결함 모듈 귀속 (정상 페어링에도 서드파티 stripped 라이브러리 크래시 대응) ──
    private String faultingModule;           // 실제 결함 프레임의 소유 모듈 basename
    private String faultingModuleVendor;     // 결함 모듈 벤더 라벨 (예: Oracle Client)
    private Boolean faultingModuleHasSymbols;// 결함 모듈 심볼 로드 여부. 미상이면 null
    private boolean selfRaisedSignal;        // 최상단이 raise/abort 등 시그널 자체-재raise 여부
    // 신뢰도 가이드 종류: EXEC_MISSING | THIRDPARTY_STRIPPED | APP_STRIPPED | OK
    private String guidanceKind;
}
