package com.heapdump.analyzer.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.Map;

@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CoreDumpAnalysisResult {
    private String filename;
    private String executableName;
    private String gdbVersion;
    private String crashSignal;           // "SIGSEGV", "SIGABRT" 등
    private String signalDescription;     // "Segmentation fault" 등
    private String coreProgramName;       // Core was generated by 에서 추출
    private List<GdbStackFrame> mainBacktrace;
    private List<GdbThreadInfo> allThreads;
    private Map<String, String> registers;
    private List<GdbSharedLib> sharedLibraries;
    private String gdbRawOutput;
    private String coreDumpTime;          // 코어 파일 생성 시각 (파일 mtime)
    private String errorMessage;
    private String analyzedAt;            // ISO-8601 문자열
    private long analysisTimeMs;
}
